// Major agricultural cities/districts across India for weather dropdown
// Grouped by region for better UX
//constants/cities.js

export const CITY_GROUPS = [
  {
    region: "North India",
    cities: [
      { name: "Ludhiana", state: "Punjab" },
      { name: "Amritsar", state: "Punjab" },
      { name: "Patiala", state: "Punjab" },
      { name: "Bathinda", state: "Punjab" },
      { name: "Karnal", state: "Haryana" },
      { name: "Hisar", state: "Haryana" },
      { name: "Rohtak", state: "Haryana" },
      { name: "Ambala", state: "Haryana" },
      { name: "Agra", state: "Uttar Pradesh" },
      { name: "Lucknow", state: "Uttar Pradesh" },
      { name: "Kanpur", state: "Uttar Pradesh" },
      { name: "Varanasi", state: "Uttar Pradesh" },
      { name: "Meerut", state: "Uttar Pradesh" },
      { name: "Moradabad", state: "Uttar Pradesh" },
      { name: "Bareilly", state: "Uttar Pradesh" },
      { name: "Dehradun", state: "Uttarakhand" },
      { name: "Haridwar", state: "Uttarakhand" },
      { name: "Shimla", state: "Himachal Pradesh" },
      { name: "Dharamsala", state: "Himachal Pradesh" },
      { name: "Srinagar", state: "Jammu and Kashmir" },
      { name: "Jammu", state: "Jammu and Kashmir" },
    ],
  },
  {
    region: "Central India",
    cities: [
      { name: "Bhopal", state: "Madhya Pradesh" },
      { name: "Indore", state: "Madhya Pradesh" },
      { name: "Jabalpur", state: "Madhya Pradesh" },
      { name: "Gwalior", state: "Madhya Pradesh" },
      { name: "Ujjain", state: "Madhya Pradesh" },
      { name: "Sagar", state: "Madhya Pradesh" },
      { name: "Raipur", state: "Chhattisgarh" },
      { name: "Bilaspur", state: "Chhattisgarh" },
      { name: "Nagpur", state: "Maharashtra" },
      { name: "Aurangabad", state: "Maharashtra" },
    ],
  },
  {
    region: "West India",
    cities: [
      { name: "Jaipur", state: "Rajasthan" },
      { name: "Jodhpur", state: "Rajasthan" },
      { name: "Ajmer", state: "Rajasthan" },
      { name: "Kota", state: "Rajasthan" },
      { name: "Bikaner", state: "Rajasthan" },
      { name: "Udaipur", state: "Rajasthan" },
      { name: "Alwar", state: "Rajasthan" },
      { name: "Ahmedabad", state: "Gujarat" },
      { name: "Surat", state: "Gujarat" },
      { name: "Rajkot", state: "Gujarat" },
      { name: "Vadodara", state: "Gujarat" },
      { name: "Anand", state: "Gujarat" },
      { name: "Junagadh", state: "Gujarat" },
      { name: "Mumbai", state: "Maharashtra" },
      { name: "Pune", state: "Maharashtra" },
      { name: "Nashik", state: "Maharashtra" },
      { name: "Kolhapur", state: "Maharashtra" },
      { name: "Solapur", state: "Maharashtra" },
      { name: "Amravati", state: "Maharashtra" },
    ],
  },
  {
    region: "South India",
    cities: [
      { name: "Hyderabad", state: "Telangana" },
      { name: "Warangal", state: "Telangana" },
      { name: "Nizamabad", state: "Telangana" },
      { name: "Karimnagar", state: "Telangana" },
      { name: "Vijayawada", state: "Andhra Pradesh" },
      { name: "Visakhapatnam", state: "Andhra Pradesh" },
      { name: "Guntur", state: "Andhra Pradesh" },
      { name: "Kurnool", state: "Andhra Pradesh" },
      { name: "Tirupati", state: "Andhra Pradesh" },
      { name: "Bengaluru", state: "Karnataka" },
      { name: "Mysuru", state: "Karnataka" },
      { name: "Hubli", state: "Karnataka" },
      { name: "Shivamogga", state: "Karnataka" },
      { name: "Davangere", state: "Karnataka" },
      { name: "Bellary", state: "Karnataka" },
      { name: "Chennai", state: "Tamil Nadu" },
      { name: "Coimbatore", state: "Tamil Nadu" },
      { name: "Madurai", state: "Tamil Nadu" },
      { name: "Salem", state: "Tamil Nadu" },
      { name: "Tiruchirapalli", state: "Tamil Nadu" },
      { name: "Thiruvananthapuram", state: "Kerala" },
      { name: "Kochi", state: "Kerala" },
      { name: "Kozhikode", state: "Kerala" },
    ],
  },
  {
    region: "East India",
    cities: [
      { name: "Patna", state: "Bihar" },
      { name: "Gaya", state: "Bihar" },
      { name: "Muzaffarpur", state: "Bihar" },
      { name: "Bhagalpur", state: "Bihar" },
      { name: "Kolkata", state: "West Bengal" },
      { name: "Siliguri", state: "West Bengal" },
      { name: "Asansol", state: "West Bengal" },
      { name: "Bardhaman", state: "West Bengal" },
      { name: "Bhubaneswar", state: "Odisha" },
      { name: "Cuttack", state: "Odisha" },
      { name: "Berhampur", state: "Odisha" },
      { name: "Ranchi", state: "Jharkhand" },
      { name: "Dhanbad", state: "Jharkhand" },
      { name: "Guwahati", state: "Assam" },
      { name: "Dibrugarh", state: "Assam" },
      { name: "Silchar", state: "Assam" },
    ],
  },
];

// Flat list for easy lookup
export const ALL_CITIES = CITY_GROUPS.flatMap((g) =>
  g.cities.map((c) => ({ ...c, region: g.region }))
);

export default ALL_CITIES;