//crops.js
export const CROP_CATEGORIES = {
  CEREALS: "Cereals & Millets",
  VEGETABLES: "Vegetables",
  FRUITS: "Fruits",
  OILSEEDS: "Oilseeds",
  PULSES: "Pulses",
  SPICES: "Spices & Condiments",
  CASH: "Cash Crops",
  FLOWERS: "Flowers",
};

export const CROPS = [
  // ── CEREALS & MILLETS ──────────────────────────────────────────
  {
    name: "Wheat",
    icon: "🌾",
    category: CROP_CATEGORIES.CEREALS,
    season: "Rabi (Nov–Mar)",
    temp: "10–25°C",
    soil: "Loamy, well-drained",
    water: "Moderate (4–5 irrigations)",
    harvest: "March–April",
    states: "Punjab, Haryana, UP, MP, Rajasthan",
    apiName: "Wheat",
  },
  {
    name: "Rice",
    icon: "🍚",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif (Jun–Nov)",
    temp: "20–35°C",
    soil: "Clayey, water-retentive",
    water: "High (flooded fields)",
    harvest: "October–November",
    states: "WB, UP, Punjab, AP, Odisha",
    apiName: "Rice",
  },
  {
    name: "Paddy",
    icon: "🌿",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif (Jun–Sep)",
    temp: "22–32°C",
    soil: "Clayey, water-logged OK",
    water: "Very High",
    harvest: "September–October",
    states: "UP, WB, Odisha, Bihar, Chhattisgarh",
    apiName: "Paddy(Common)",
  },
  {
    name: "Maize",
    icon: "🌽",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif (Jun–Sep)",
    temp: "21–27°C",
    soil: "Sandy loam to loam",
    water: "Moderate",
    harvest: "September–October",
    states: "Karnataka, AP, Rajasthan, Bihar, MP",
    apiName: "Maize",
  },
  {
    name: "Bajra",
    icon: "🌾",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif (Jun–Sep)",
    temp: "25–35°C",
    soil: "Sandy loam, light soils",
    water: "Low (drought tolerant)",
    harvest: "September–November",
    states: "Rajasthan, Gujarat, Haryana, UP, Maharashtra",
    apiName: "Bajra(Pearl Millet/Cumbu)",
  },
  {
    name: "Jowar",
    icon: "🌾",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif & Rabi",
    temp: "25–30°C",
    soil: "Medium to heavy, well-drained",
    water: "Low–Moderate",
    harvest: "Oct–Nov (Kharif), Feb–Mar (Rabi)",
    states: "Maharashtra, Karnataka, MP, Rajasthan, AP",
    apiName: "Jowar(Sorghum)",
  },
  {
    name: "Barley",
    icon: "🌾",
    category: CROP_CATEGORIES.CEREALS,
    season: "Rabi (Oct–Mar)",
    temp: "12–25°C",
    soil: "Light loamy, well-drained",
    water: "Low (2–3 irrigations)",
    harvest: "March–April",
    states: "UP, Rajasthan, MP, Haryana, Punjab",
    apiName: "Barley",
  },
  {
    name: "Ragi",
    icon: "🌾",
    category: CROP_CATEGORIES.CEREALS,
    season: "Kharif (Jun–Sep)",
    temp: "20–30°C",
    soil: "Sandy loam, red laterite",
    water: "Low–Moderate",
    harvest: "October–November",
    states: "Karnataka, AP, Tamil Nadu, Maharashtra, Odisha",
    apiName: "Ragi (Finger Millet/Mandua)",
  },

  // ── VEGETABLES ─────────────────────────────────────────────────
  {
    name: "Onion",
    icon: "🧅",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Oct–Jan)",
    temp: "13–24°C",
    soil: "Sandy loam, well-drained",
    water: "Low–Moderate",
    harvest: "February–May",
    states: "Maharashtra, Karnataka, MP, Gujarat, Rajasthan",
    apiName: "Onion",
  },
  {
    name: "Potato",
    icon: "🥔",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Oct–Dec)",
    temp: "15–20°C",
    soil: "Sandy loam, loose",
    water: "Moderate (frequent light)",
    harvest: "January–March",
    states: "UP, WB, Bihar, Punjab, Gujarat",
    apiName: "Potato",
  },
  {
    name: "Tomato",
    icon: "🍅",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Year-round",
    temp: "18–27°C",
    soil: "Sandy loam, rich organic",
    water: "Moderate (drip ideal)",
    harvest: "60–80 days after planting",
    states: "AP, Karnataka, Maharashtra, MP, Gujarat",
    apiName: "Tomato",
  },
  {
    name: "Brinjal",
    icon: "🍆",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Year-round",
    temp: "22–32°C",
    soil: "Well-drained loam",
    water: "Moderate",
    harvest: "60–90 days after planting",
    states: "WB, Odisha, Bihar, Gujarat, Maharashtra",
    apiName: "Brinjal",
  },
  {
    name: "Cabbage",
    icon: "🥬",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Sep–Jan)",
    temp: "15–20°C",
    soil: "Loamy, well-drained",
    water: "Moderate",
    harvest: "December–March",
    states: "WB, Odisha, Bihar, Karnataka, HP",
    apiName: "Cabbage",
  },
  {
    name: "Cauliflower",
    icon: "🥦",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Sep–Jan)",
    temp: "15–20°C",
    soil: "Well-drained loam",
    water: "Moderate",
    harvest: "November–February",
    states: "WB, Bihar, UP, MP, Odisha",
    apiName: "Cauliflower",
  },
  {
    name: "Peas",
    icon: "🫛",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Oct–Dec)",
    temp: "10–18°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "January–March",
    states: "UP, HP, Punjab, Haryana, WB",
    apiName: "Green Peas",
  },
  {
    name: "Capsicum",
    icon: "🫑",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Year-round",
    temp: "18–25°C",
    soil: "Sandy loam, rich organic",
    water: "Moderate (drip ideal)",
    harvest: "70–90 days after planting",
    states: "HP, Karnataka, Maharashtra, WB, UP",
    apiName: "Capsicum",
  },
  {
    name: "Garlic",
    icon: "🧄",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Oct–Nov)",
    temp: "12–24°C",
    soil: "Sandy loam, fertile",
    water: "Low–Moderate",
    harvest: "March–May",
    states: "MP, Gujarat, Rajasthan, UP, Maharashtra",
    apiName: "Garlic",
  },
  {
    name: "Ginger",
    icon: "🫚",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Kharif (Apr–May)",
    temp: "20–30°C",
    soil: "Well-drained loam, rich organic",
    water: "Moderate–High",
    harvest: "December–February",
    states: "Kerala, Karnataka, AP, Odisha, Assam",
    apiName: "Ginger",
  },
  {
    name: "Bitter Gourd",
    icon: "🥒",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Summer & Kharif",
    temp: "24–27°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "55–60 days after sowing",
    states: "UP, WB, Bihar, AP, Karnataka",
    apiName: "Bitter Gourd",
  },
  {
    name: "Bottle Gourd",
    icon: "🥒",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Summer & Kharif",
    temp: "25–35°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "60–70 days after sowing",
    states: "UP, Bihar, WB, Haryana, Punjab",
    apiName: "Bottle Gourd",
  },
  {
    name: "Carrot",
    icon: "🥕",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Sep–Nov)",
    temp: "15–20°C",
    soil: "Sandy loam, deep loose",
    water: "Moderate",
    harvest: "December–February",
    states: "Punjab, HP, Haryana, Karnataka, Rajasthan",
    apiName: "Carrot",
  },
  {
    name: "Radish",
    icon: "🥗",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Sep–Nov)",
    temp: "10–15°C",
    soil: "Sandy loam, loose",
    water: "Moderate",
    harvest: "30–45 days after sowing",
    states: "Punjab, UP, Haryana, WB, HP",
    apiName: "Raddish",
  },
  {
    name: "Spinach",
    icon: "🥬",
    category: CROP_CATEGORIES.VEGETABLES,
    season: "Rabi (Sep–Feb)",
    temp: "15–20°C",
    soil: "Loamy, rich organic",
    water: "Moderate",
    harvest: "40–50 days after sowing",
    states: "UP, Haryana, Punjab, WB, HP",
    apiName: "Spinach",
  },

  // ── FRUITS ─────────────────────────────────────────────────────
  {
    name: "Banana",
    icon: "🍌",
    category: CROP_CATEGORIES.FRUITS,
    season: "Year-round",
    temp: "26–35°C",
    soil: "Deep loamy, rich",
    water: "High (irrigation needed)",
    harvest: "12–15 months after planting",
    states: "Tamil Nadu, Maharashtra, Gujarat, AP, Karnataka",
    apiName: "Banana",
  },
  {
    name: "Mango",
    icon: "🥭",
    category: CROP_CATEGORIES.FRUITS,
    season: "Summer (Mar–Jun)",
    temp: "24–27°C",
    soil: "Deep loamy, well-drained",
    water: "Low–Moderate",
    harvest: "April–July",
    states: "UP, AP, Karnataka, Bihar, Gujarat",
    apiName: "Mango",
  },
  {
    name: "Grapes",
    icon: "🍇",
    category: CROP_CATEGORIES.FRUITS,
    season: "Rabi (harvest Feb–May)",
    temp: "15–40°C",
    soil: "Well-drained loam, gravelly",
    water: "Moderate (drip ideal)",
    harvest: "February–May",
    states: "Maharashtra, Karnataka, AP, Tamil Nadu",
    apiName: "Grapes",
  },
  {
    name: "Pomegranate",
    icon: "🍎",
    category: CROP_CATEGORIES.FRUITS,
    season: "Year-round",
    temp: "25–35°C",
    soil: "Well-drained loam",
    water: "Low–Moderate (drought tolerant)",
    harvest: "5–7 months after flowering",
    states: "Maharashtra, Gujarat, Karnataka, Rajasthan, AP",
    apiName: "Pomegranate",
  },
  {
    name: "Papaya",
    icon: "🍈",
    category: CROP_CATEGORIES.FRUITS,
    season: "Year-round",
    temp: "25–30°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "9–11 months after planting",
    states: "AP, Karnataka, Gujarat, WB, Maharashtra",
    apiName: "Papaya",
  },
  {
    name: "Watermelon",
    icon: "🍉",
    category: CROP_CATEGORIES.FRUITS,
    season: "Summer (Feb–Apr)",
    temp: "24–27°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "80–110 days after sowing",
    states: "UP, Karnataka, AP, Tamil Nadu, Rajasthan",
    apiName: "Water Melon",
  },
  {
    name: "Guava",
    icon: "🍏",
    category: CROP_CATEGORIES.FRUITS,
    season: "Year-round (main crop winter)",
    temp: "23–28°C",
    soil: "Well-drained loam, sandy",
    water: "Low–Moderate",
    harvest: "October–March",
    states: "UP, MP, Bihar, Maharashtra, AP",
    apiName: "Guava",
  },
  {
    name: "Lemon",
    icon: "🍋",
    category: CROP_CATEGORIES.FRUITS,
    season: "Year-round",
    temp: "20–35°C",
    soil: "Well-drained loam",
    water: "Low–Moderate",
    harvest: "Year-round",
    states: "AP, Maharashtra, Tamil Nadu, Gujarat, Rajasthan",
    apiName: "Lemon",
  },

  // ── OILSEEDS ───────────────────────────────────────────────────
  {
    name: "Mustard",
    icon: "🌻",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Rabi (Oct–Feb)",
    temp: "10–25°C",
    soil: "Loamy, well-drained",
    water: "Low (1–2 irrigations)",
    harvest: "February–March",
    states: "Rajasthan, UP, Haryana, MP, Gujarat",
    apiName: "Mustard",
  },
  {
    name: "Groundnut",
    icon: "🥜",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Kharif (Jun–Sep)",
    temp: "25–30°C",
    soil: "Sandy loam, light",
    water: "Moderate",
    harvest: "September–November",
    states: "Gujarat, AP, Rajasthan, Tamil Nadu, Karnataka",
    apiName: "Groundnut",
  },
  {
    name: "Soyabean",
    icon: "🫘",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Kharif (Jun–Sep)",
    temp: "20–30°C",
    soil: "Well-drained loam",
    water: "Moderate",
    harvest: "September–October",
    states: "MP, Maharashtra, Rajasthan, Karnataka, AP",
    apiName: "Soyabean",
  },
  {
    name: "Sunflower",
    icon: "🌻",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Rabi & Kharif",
    temp: "20–25°C",
    soil: "Well-drained loam",
    water: "Moderate",
    harvest: "90–100 days after sowing",
    states: "Karnataka, AP, Maharashtra, UP, Haryana",
    apiName: "Sunflower",
  },
  {
    name: "Sesame",
    icon: "🌿",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Kharif (Jun–Jul)",
    temp: "25–35°C",
    soil: "Sandy loam, well-drained",
    water: "Low",
    harvest: "September–October",
    states: "Gujarat, Rajasthan, UP, WB, Tamil Nadu",
    apiName: "Sesamum(Sesame/Gingelly)",
  },
  {
    name: "Castor",
    icon: "🌿",
    category: CROP_CATEGORIES.OILSEEDS,
    season: "Kharif (Jun–Aug)",
    temp: "20–35°C",
    soil: "Well-drained, light to medium",
    water: "Low (drought tolerant)",
    harvest: "November–February",
    states: "Gujarat, Rajasthan, AP, Karnataka, Odisha",
    apiName: "Castor Seed",
  },

  // ── PULSES ─────────────────────────────────────────────────────
  {
    name: "Chickpea",
    icon: "🫘",
    category: CROP_CATEGORIES.PULSES,
    season: "Rabi (Oct–Nov)",
    temp: "20–30°C",
    soil: "Sandy loam to loam, well-drained",
    water: "Low (1–2 irrigations)",
    harvest: "February–March",
    states: "MP, Rajasthan, Maharashtra, UP, AP",
    apiName: "Gram",
  },
  {
    name: "Lentil",
    icon: "🫘",
    category: CROP_CATEGORIES.PULSES,
    season: "Rabi (Oct–Nov)",
    temp: "18–30°C",
    soil: "Loamy, well-drained",
    water: "Low",
    harvest: "March–April",
    states: "MP, UP, Bihar, Rajasthan, WB",
    apiName: "Masur Dal",
  },
  {
    name: "Moong Dal",
    icon: "🫘",
    category: CROP_CATEGORIES.PULSES,
    season: "Kharif & Zaid",
    temp: "25–35°C",
    soil: "Sandy loam, well-drained",
    water: "Low–Moderate",
    harvest: "60–90 days after sowing",
    states: "Rajasthan, Maharashtra, AP, Karnataka, MP",
    apiName: "Moong (Whole)",
  },
  {
    name: "Urad Dal",
    icon: "🫘",
    category: CROP_CATEGORIES.PULSES,
    season: "Kharif (Jun–Jul)",
    temp: "25–35°C",
    soil: "Sandy loam, well-drained",
    water: "Low–Moderate",
    harvest: "September–October",
    states: "UP, MP, Rajasthan, Maharashtra, AP",
    apiName: "Black Gram (Urd Beans)(Whole)",
  },
  {
    name: "Pigeon Pea",
    icon: "🫘",
    category: CROP_CATEGORIES.PULSES,
    season: "Kharif (Jun–Jul)",
    temp: "25–35°C",
    soil: "Well-drained loam",
    water: "Low (drought tolerant)",
    harvest: "November–January",
    states: "Maharashtra, UP, Karnataka, MP, AP",
    apiName: "Arhar (Tur/Pigeon Pea)(Whole)",
  },

  // ── SPICES ─────────────────────────────────────────────────────
  {
    name: "Turmeric",
    icon: "🟡",
    category: CROP_CATEGORIES.SPICES,
    season: "Kharif (May–Jun)",
    temp: "20–30°C",
    soil: "Loamy, well-drained",
    water: "Moderate–High",
    harvest: "January–March",
    states: "Telangana, AP, Tamil Nadu, Karnataka, Odisha",
    apiName: "Turmeric",
  },
  {
    name: "Chilli",
    icon: "🌶️",
    category: CROP_CATEGORIES.SPICES,
    season: "Kharif & Rabi",
    temp: "20–30°C",
    soil: "Sandy loam, well-drained",
    water: "Moderate",
    harvest: "90–120 days after transplanting",
    states: "AP, Karnataka, Maharashtra, MP, Rajasthan",
    apiName: "Dry Chillies",
  },
  {
    name: "Coriander",
    icon: "🌿",
    category: CROP_CATEGORIES.SPICES,
    season: "Rabi (Oct–Nov)",
    temp: "20–25°C",
    soil: "Loamy, well-drained",
    water: "Low–Moderate",
    harvest: "February–March",
    states: "Rajasthan, MP, Gujarat, AP, Karnataka",
    apiName: "Coriander(Leaves)",
  },
  {
    name: "Cumin",
    icon: "🌿",
    category: CROP_CATEGORIES.SPICES,
    season: "Rabi (Nov–Dec)",
    temp: "10–30°C",
    soil: "Sandy loam, well-drained",
    water: "Low (2–3 irrigations)",
    harvest: "February–March",
    states: "Rajasthan, Gujarat",
    apiName: "Cummin Seed(Jeera)",
  },
  {
    name: "Fenugreek",
    icon: "🌿",
    category: CROP_CATEGORIES.SPICES,
    season: "Rabi (Oct–Nov)",
    temp: "10–25°C",
    soil: "Loamy, well-drained",
    water: "Low–Moderate",
    harvest: "December–February",
    states: "Rajasthan, Gujarat, MP, UP, Haryana",
    apiName: "Methi(Leaves)",
  },

  // ── CASH CROPS ─────────────────────────────────────────────────
  {
    name: "Sugarcane",
    icon: "🎋",
    category: CROP_CATEGORIES.CASH,
    season: "Year-round (plant Feb–Mar)",
    temp: "20–35°C",
    soil: "Loamy, well-drained",
    water: "Very High",
    harvest: "12–18 months",
    states: "UP, Maharashtra, Karnataka, Tamil Nadu, Gujarat",
    apiName: "Sugarcane",
  },
  {
    name: "Cotton",
    icon: "☁️",
    category: CROP_CATEGORIES.CASH,
    season: "Kharif (May–Sep)",
    temp: "21–35°C",
    soil: "Black cotton soil",
    water: "Moderate–High",
    harvest: "November–January",
    states: "Gujarat, Maharashtra, AP, Haryana, Punjab",
    apiName: "Cotton",
  },
  {
    name: "Jute",
    icon: "🌿",
    category: CROP_CATEGORIES.CASH,
    season: "Kharif (Mar–Apr)",
    temp: "24–37°C",
    soil: "Alluvial loam",
    water: "High",
    harvest: "June–September",
    states: "WB, Bihar, Assam, Odisha, Meghalaya",
    apiName: "Jute",
  },
  {
    name: "Tobacco",
    icon: "🌿",
    category: CROP_CATEGORIES.CASH,
    season: "Rabi (Sep–Nov)",
    temp: "20–30°C",
    soil: "Sandy loam, light",
    water: "Moderate",
    harvest: "February–April",
    states: "AP, Karnataka, Gujarat, UP, Bihar",
    apiName: "Tobacco",
  },
];

export default CROPS;