const STATE_DISTRICTS = {
  "Punjab": [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "S.A.S Nagar",
    "SAS Nagar",
    "Kharar",
    "Hoshiarpur",
    "Gurdaspur",
    "Firozpur",
    "Sangrur",
    "Moga",
    "Faridkot",
    "Muktsar",
    "Mansa",
    "Barnala",
    "Fatehgarh Sahib",
    "Rupnagar",
    "Nawanshahr",
    "Kapurthala",
    "Tarn Taran",
    "Pathankot"
  ],
  "Haryana": [
    "Hisar",
    "Karnal",
    "Rohtak",
    "Ambala",
    "Kurukshetra",
    "Sirsa",
    "Sonipat",
    "Panipat",
    "Fatehabad",
    "Jind",
    "Kaithal",
    "Yamunanagar",
    "Bhiwani",
    "Rewari",
    "Mahendragarh",
    "Gurugram",
    "Faridabad",
    "Palwal",
    "Mewat",
    "Jhajjar"
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Allahabad",
    "Prayagraj",
    "Bareilly",
    "Gorakhpur",
    "Kanpur",
    "Lucknow",
    "Mathura",
    "Meerut",
    "Varanasi",
    "Moradabad",
    "Muzaffarnagar",
    "Saharanpur",
    "Shahjahanpur",
    "Sitapur",
    "Lakhimpur Kheri",
    "Hardoi",
    "Unnao",
    "Etawah",
    "Mainpuri",
    "Firozabad",
    "Bulandshahr",
    "Hapur",
    "Ghaziabad"
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Mandsaur",
    "Ratlam",
    "Neemuch",
    "Dewas",
    "Shajapur",
    "Vidisha",
    "Raisen",
    "Hoshangabad",
    "Betul",
    "Chhindwara",
    "Seoni",
    "Narsinghpur",
    "Damoh",
    "Katni",
    "Satna",
    "Rewa",
    "Shahdol",
    "Dhar",
    "Jhabua",
    "Khargone",
    "Barwani",
    "Khandwa",
    "Burhanpur"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Ahmednagar",
    "Amravati",
    "Akola",
    "Washim",
    "Buldhana",
    "Yavatmal",
    "Wardha",
    "Bhandara",
    "Gondia",
    "Chandrapur",
    "Gadchiroli",
    "Nanded",
    "Latur",
    "Osmanabad",
    "Jalna",
    "Parbhani",
    "Hingoli",
    "Dhule",
    "Jalgaon",
    "Nandurbar",
    "Ratnagiri",
    "Sindhudurg",
    "Raigad",
    "Thane",
    "Palghar",
    "Satara",
    "Sangli"
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Nagaur",
    "Pali",
    "Barmer",
    "Jalore",
    "Sirohi",
    "Jalor",
    "Churu",
    "Jhunjhunu",
    "Hanumangarh",
    "Ganganagar",
    "Sri Ganganagar",
    "Dungarpur",
    "Banswara",
    "Chittorgarh",
    "Bhilwara",
    "Tonk",
    "Sawai Madhopur",
    "Karauli",
    "Dausa",
    "Dholpur",
    "Bundi",
    "Baran",
    "Jhalawar",
    "Udaipur",
    "Rajsamand",
    "Pratapgarh"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Mehsana",
    "Patan",
    "Banaskantha",
    "Sabarkantha",
    "Arvalli",
    "Aravalli",
    "Kheda",
    "Anand",
    "Panchmahal",
    "Dahod",
    "Narmada",
    "Bharuch",
    "Surat",
    "Tapi",
    "Navsari",
    "Valsad",
    "Dang",
    "Amreli",
    "Botad",
    "Gir Somnath",
    "Devbhoomi Dwarka",
    "Porbandar",
    "Morbi",
    "Surendranagar",
    "Chhota Udaipur"
  ],
  "Andhra Pradesh": [
    "Guntur",
    "Krishna",
    "West Godavari",
    "East Godavari",
    "Visakhapatnam",
    "Kurnool",
    "Nellore",
    "Chittoor",
    "Kadapa",
    "Anantapur",
    "Prakasam",
    "Srikakulam",
    "Vizianagaram"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Nalgonda",
    "Mahbubnagar",
    "Adilabad",
    "Medak",
    "Rangareddy"
  ],
  "Karnataka": [
    "Bangalore",
    "Bengaluru",
    "Mysore",
    "Hubli",
    "Dharwad",
    "Belgaum",
    "Belagavi",
    "Gulbarga",
    "Kalaburagi",
    "Raichur",
    "Bijapur",
    "Vijayapura",
    "Bellary",
    "Ballari",
    "Tumkur",
    "Tumakuru",
    "Shimoga",
    "Shivamogga",
    "Davangere",
    "Chitradurga",
    "Hassan",
    "Mangalore",
    "Dakshina Kannada",
    "Udupi",
    "Kodagu",
    "Chikmagalur",
    "Chikkamagaluru",
    "Kolar",
    "Chikkaballapura",
    "Bagalkot",
    "Gadag",
    "Haveri",
    "Koppal",
    "Yadgir",
    "Bidar",
    "Chamarajanagar",
    "Mandya",
    "Ramanagara"
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Thanjavur",
    "Vellore",
    "Dindigul",
    "Cuddalore",
    "Villupuram",
    "Thiruvannamalai",
    "Krishnagiri",
    "Dharmapuri",
    "Namakkal",
    "Karur",
    "Tiruvallur",
    "Kancheepuram"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    "Purnia",
    "Samastipur",
    "Begusarai",
    "Siwan",
    "Chapra",
    "Saran",
    "Vaishali",
    "Nalanda",
    "Nawada",
    "Aurangabad",
    "Rohtas",
    "Kaimur",
    "Buxar",
    "Bhojpur",
    "Arwal",
    "Jehanabad",
    "Madhubani",
    "Sitamarhi",
    "Sheohar",
    "Supaul",
    "Araria",
    "Kishanganj",
    "Katihar",
    "Madhepura",
    "Saharsa",
    "Khagaria"
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Burdwan",
    "Bardhaman",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "South 24 Parganas",
    "Hooghly",
    "Medinipur",
    "Midnapore",
    "Bankura",
    "Purulia",
    "Birbhum",
    "Malda",
    "Dinajpur",
    "Jalpaiguri",
    "Darjeeling",
    "Cooch Behar"
  ],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Berhampur",
    "Ganjam",
    "Puri",
    "Khurda",
    "Balasore",
    "Bhadrak",
    "Jajpur",
    "Kendrapara",
    "Jagatsinghpur",
    "Dhenkanal",
    "Angul",
    "Sambalpur",
    "Bargarh",
    "Jharsuguda",
    "Sundargarh",
    "Koraput",
    "Rayagada",
    "Kalahandi",
    "Bolangir",
    "Nuapada",
    "Boudh"
  ],
  "Assam": [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Sibsagar",
    "Lakhimpur",
    "Darrang",
    "Bongaigaon",
    "Cachar",
    "Kamrup",
    "Sonitpur",
    "Golaghat",
    "Karbi Anglong"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Kullu",
    "Mandi",
    "Kangra",
    "Solan",
    "Una",
    "Hamirpur",
    "Bilaspur",
    "Chamba",
    "Sirmaur",
    "Kinnaur"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Udham Singh Nagar",
    "Almora",
    "Pauri Garhwal",
    "Tehri Garhwal",
    "Chamoli",
    "Rudraprayag",
    "Pithoragarh",
    "Bageshwar",
    "Champawat"
  ],
  "Jharkhand": [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Giridih",
    "Deoghar",
    "Dumka",
    "Gumla",
    "Lohardaga",
    "Palamu",
    "Chatra",
    "Koderma",
    "Ramgarh",
    "Khunti",
    "Simdega",
    "West Singhbhum",
    "East Singhbhum",
    "Saraikela Kharsawan",
    "Pakur",
    "Godda",
    "Sahibganj",
    "Jamtara",
    "Latehar"
  ],
  "Chhattisgarh": [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Rajnandgaon",
    "Korba",
    "Raigarh",
    "Janjgir",
    "Jashpur",
    "Surguja",
    "Kanker",
    "Bastar",
    "Dantewada",
    "Narayanpur",
    "Bijapur",
    "Sukma",
    "Kondagaon",
    "Gariaband",
    "Balod",
    "Bemetara",
    "Mungeli",
    "Kabirdham",
    "Balodabazar",
    "Mahasamund",
    "Dhamtari",
    "Surajpur",
    "Balrampur",
    "Koriya"
  ],
  "Kerala": [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Malappuram",
    "Palakkad",
    "Kannur",
    "Kollam",
    "Kottayam",
    "Kasaragod",
    "Idukki",
    "Pathanamthitta",
    "Alappuzha",
    "Wayanad"
  ],
  "Arunachal Pradesh": ["Itanagar", "Tawang", "Ziro", "Pasighat"],
  "Goa": ["North Goa", "South Goa", "Panaji", "Margao"],
  "Manipur": ["Imphal", "Thoubal", "Churachandpur"],
  "Meghalaya": ["Shillong", "Tura", "Jowai"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar"],
  "Delhi": ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Central Delhi"],
  "Jammu & Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur"],
  "Ladakh": ["Leh", "Kargil"],
  "Puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam"]
};
export default STATE_DISTRICTS;